# fly.toml app configuration file...

app = 'serienbriefassistent'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8000      # <-- Fly klopft an dieser Tür an
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[processes]
  app = "uvicorn main:app --host 0.0.0.0 --port 8000"